apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-job
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:v1.23.0
        args:
        - "--context=__CONTEXT_URL__#refs/heads/main"
        - "--dockerfile=Dockerfile"
        - "--destination=__IMAGE_DEST__"
        - "--cache=true"
        - "--cache-ttl=24h"
        volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker/
          readOnly: true
      volumes:
      - name: docker-config
        secret:
          secretName: dockerhub-creds
          items:
          - key: .dockerconfigjson
            path: config.json
