{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-init-config
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  config.yaml: {{ .Values.initialConfig | toYaml | nindent 4 }}
{{- end }}
