{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-init-config
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ .Files.Get "../../config/config.yaml" | indent 4 }}
{{- end }}
