{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-init-data
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  posts.yaml: {{ .Values.initialData.posts | toYaml | nindent 4 }}
  services.yaml: {{ .Values.initialData.services | toYaml | nindent 4 }}
{{- end }}
